### ISSUE TITLE
Error installing. Package not in GOROOT

### ISSUE THREAD

**Issue by Silentsoul04** [aydinnyunus/exifLooter#2]
While installing it is giving error: package is not in GOROOT

Go version:
version go1.18.4 linux/amd64

Exiftool path:
usr/bin/exiftool

error when Installation:
`go install github.com/aydinnyunus/exifLooter@latest`

`
../gopath/pkg/mod/github.com/aydinnyunus/exif!looter@v0.0.0-20220730205424-a8d9d04e33a6/main.go:7:8: package exifLooter/cmd is not in GOROOT (/usr/local/go/src/exifLooter/cmd)
`

**Comment by aydinnyunus** [comment]
Hi, can you try again ?

**Comment by Silentsoul04** [comment]
Thanks @aydinnyunus ! It is working now.
