### ISSUE TITLE
Images not Vulnerable

### ISSUE THREAD

**Issue by ManChrys** [aydinnyunus/exifLooter#3]
C:\labpano_github\exifLooter\images> exifLooter --image GPS_frame00000.jpeg
These image/images not Vulnerable

Hello. Whats the "These image/images not Vulnerable" means ? how can i fix it ? :P Thank you :D

My photos are from labpano 360 camera

![1](https://user-images.githubusercontent.com/67521662/182693353-5c59085f-c488-4f14-97c4-5fc2d37c4ccf.png)

**Comment by aydinnyunus** [comment]
Image not Vulnerable means There is not any Geolocation Metadata on those images.

**Comment by ManChrys** [comment]
ok thank you :)
