### ISSUE TITLE
exifLooter: command not found

### ISSUE THREAD

**Issue by andre-santos1** [aydinnyunus/exifLooter#5]
I installed using:

`go install github.com/aydinnyunus/exifLooter@latest`

Then I navigated to the folder  where my target test file was located, opened terminal there and then runned:

 `exifLooter --image IMG_0001.JPG`

Doing that I get the error:

`exifLooter: command not found`

I also tried to run the following command from terminal:

`exifLooter --image /home/osint/Downloads/IMG_0001.JPG`

Same error:

`exifLooter: command not found`

I have go installed since i ran:

`sudo apt install golang-go -y`

What should I do?

**Comment by aydinnyunus** [comment]
What is your Golang Version ?

**Comment by andre-santos1** [comment]
go version go1.18.1 linux/amd64

**Comment by wacs** [comment]
> I installed using:
> 
> `go install github.com/aydinnyunus/exifLooter@latest`
> 
> Then I navigated to the folder where my target test file was located, opened terminal there and then runned:
> 
> `exifLooter --image IMG_0001.JPG`
> 
> Doing that I get the error:
> 
> `exifLooter: command not found`
> 
> I also tried to run the following command from terminal:
> 
> `exifLooter --image /home/osint/Downloads/IMG_0001.JPG`
> 
> Same error:
> 
> `exifLooter: command not found`
> 
> I have go installed since i ran:
> 
> `sudo apt install golang-go -y`
> 
> What should I do?

Navigate where the application was installed. Do a search of the application with "find / -iname exifLooter".

This search give me the following result: /home/myusername/go/bin

Hope this be useful to you.

**Comment by aydinnyunus** [comment]
Hi,

You install the package but probably installed folder is not on your PATH variable. You can add it searching according to your Operating System.

In Kali Linux, you can install the package with `apt-get install exiflooter`
