### ISSUE TITLE
Empty LICENSE file

### ISSUE THREAD

**Issue by aquilamacedo** [aydinnyunus/exifLooter#7]
I'm currently in the process of packaging `exiflooter` for **Debian**. While examining the repository, I noticed that the LICENSE file appears to be empty. To ensure compliance and accurate packaging, I'd appreciate clarification on the specific license that applies to `exiflooter`.

Could you kindly provide information about the type of license used for exiflooter? This will assist in aligning with Debian's packaging guidelines and ensuring proper licensing attribution.

Thanks in advance for your prompt response!

**Comment by aydinnyunus** [comment]
Hi,

Thank you for your request. I created the LICENSE file with the following commit https://github.com/aydinnyunus/exifLooter/commit/22e4700b71a6d148ff3219801550f3686381e202
